In [15]:
from pathlib import Path
import pandas as pd
import matplotlib.pyplot as plt
import pandas as pd

In [17]:
#abrir grd parquet para explorar los datos y hacer un análisis de los mismos.
grd_parquet = pd.read_parquet('/Users/maria/Documents/Business Intehlligence/W1/grd_procesado.parquet')
grd_parquet.head()  # Mostrar las primeras filas del DataFrame para explorar los datos

,COD_ESTABLECIMIENTO,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,PROVINCIA,COMUNA_REGISTRADA,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,...,CAMAS_CRITICAS,POB_MULT_ESTAB,COMUNA_CON_ESTAB_AC,FALLECIDO,CRITICAS_PROP,CAMAS_COMUNA,CRITICAS_COMUNA,CAMAS_1000HAB,CRITICAS_1000HAB,TASA_MORTALIDAD_COMUNA
0,118100,467373,HOMBRE,1969-09-10,CONCEPCION,SAN PEDRO DE LA PAZ,FONASA INSTITUCIONAL - (MAI) B,CONCEPCIÓN,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963
1,118100,562854,HOMBRE,1956-02-07,CONCEPCION,CORONEL,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,113,0.090303,1,0,0.128118,882,113,3.717488,0.476277,0.117963
2,118100,199980,MUJER,1960-02-28,CONCEPCION,SAN PEDRO DE LA PAZ,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,APS CONSULTORIO (CESFAM),URGENCIA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963
3,118100,857926,MUJER,1933-01-12,CONCEPCION,CHIGUAYANTE,FONASA INSTITUCIONAL - (MAI) D,CONCEPCIÓN,"OTRAS INSTITUCIONES SALUD (CLÍNICAS PRIVADAS, ...",URGENCIA,...,113,0.090303,0,1,0.128118,882,113,3.717488,0.476277,0.117963
4,118100,284629,HOMBRE,1951-05-03,CURICO,TENO,FONASA INSTITUCIONAL - (MAI) C,DEL MAULE,"CENTRO ESPECIALIDADES (CDT, CRS, CONSULTORIO A...",PROGRAMADA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963

In [18]:
#valores nulos en el parquet
grd_parquet.isnull().sum()  # Contar los valores nulos en cada columna del DataFrame parquet

COD_ESTABLECIMIENTO          0
CIP_ENCRIPTADO               0
SEXO                         0
FECHA_NACIMIENTO             0
PROVINCIA                    0
COMUNA_REGISTRADA            0
PREVISION                    0
SERVICIO_SALUD               0
TIPO_PROCEDENCIA             0
TIPO_INGRESO                 0
FECHA_INGRESO                0
FECHAALTA                    0
TIPOALTA                     0
DIAGNOSTICO1                 0
DIAGNOSTICO2                 9
DIAGNOSTICO3              4920
PROCEDIMIENTO1             127
PROCEDIMIENTO2            2329
IR_29301_COD_GRD             0
IR_29301_PESO                0
IR_29301_SEVERIDAD           0
IR_29301_MORTALIDAD          0
YEAR                         0
EDAD                         0
DIAS_ESTANCIA                0
N_COMORBILIDADES             0
N_PROCEDIMIENTOS             0
INDICE_CHARLSON              0
DESCRIPCION                  0
SECCION                      0
COD_REGION                   0
REGION                       0
ESTABLECIMIENTO              0
COD_COMUNA                   0
COMUNA_ESTAB                 0
LATITUD                      0
LONGITUD                     0
PRESTADOR                    0
COMPLEJIDAD_ESTAB            0
POB_COMUNA                   0
POB_REGION                   0
CAMAS_TOTALES                0
CAMAS_CRITICAS               0
POB_MULT_ESTAB               0
COMUNA_CON_ESTAB_AC          0
FALLECIDO                    0
CRITICAS_PROP                0
CAMAS_COMUNA                 0
CRITICAS_COMUNA              0
CAMAS_1000HAB                0
CRITICAS_1000HAB             0
TASA_MORTALIDAD_COMUNA       0
dtype: int64

In [19]:
grd_femenino = grd_parquet[grd_parquet['SEXO'] == 'MUJER']
grd_femenino.head()  # Mostrar las primeras filas del DataFrame filtrado por sexo femenino

,COD_ESTABLECIMIENTO,CIP_ENCRIPTADO,SEXO,FECHA_NACIMIENTO,PROVINCIA,COMUNA_REGISTRADA,PREVISION,SERVICIO_SALUD,TIPO_PROCEDENCIA,TIPO_INGRESO,...,CAMAS_CRITICAS,POB_MULT_ESTAB,COMUNA_CON_ESTAB_AC,FALLECIDO,CRITICAS_PROP,CAMAS_COMUNA,CRITICAS_COMUNA,CAMAS_1000HAB,CRITICAS_1000HAB,TASA_MORTALIDAD_COMUNA
2,118100,199980,MUJER,1960-02-28,CONCEPCION,SAN PEDRO DE LA PAZ,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,APS CONSULTORIO (CESFAM),URGENCIA,...,113,0.090303,0,0,0.128118,882,113,3.717488,0.476277,0.117963
3,118100,857926,MUJER,1933-01-12,CONCEPCION,CHIGUAYANTE,FONASA INSTITUCIONAL - (MAI) D,CONCEPCIÓN,"OTRAS INSTITUCIONES SALUD (CLÍNICAS PRIVADAS, ...",URGENCIA,...,113,0.090303,0,1,0.128118,882,113,3.717488,0.476277,0.117963
9,116110,900702,MUJER,1947-05-10,LINARES,PARRAL,FONASA INSTITUCIONAL - (MAI) B,DEL MAULE,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,0,0.135324,1,0,0.0,102,0,2.309155,0.0,0.211155
11,118100,1260221,MUJER,1959-10-19,CONCEPCION,CORONEL,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,OTROS HOSPITALES DE LA RED,URGENCIA,...,113,0.090303,1,0,0.128118,882,113,3.717488,0.476277,0.117963
13,118100,1192972,MUJER,1993-12-29,CONCEPCION,CONCEPCION,FONASA INSTITUCIONAL - (MAI) A,CONCEPCIÓN,SERVICIO EMERGENCIA (DOMICILIO),URGENCIA,...,113,0.090303,1,0,0.128118,882,113,3.717488,0.476277,0.117963

In [20]:
grd_femenino.shape

(154431, 52)

In [21]:
grd_femenino.columns  # Mostrar todas las columnas del DataFrame filtrado por sexo femenino

Index(['COD_ESTABLECIMIENTO', 'CIP_ENCRIPTADO', 'SEXO', 'FECHA_NACIMIENTO',
       'PROVINCIA', 'COMUNA_REGISTRADA', 'PREVISION', 'SERVICIO_SALUD',
       'TIPO_PROCEDENCIA', 'TIPO_INGRESO', 'FECHA_INGRESO', 'FECHAALTA',
       'TIPOALTA', 'DIAGNOSTICO1', 'DIAGNOSTICO2', 'DIAGNOSTICO3',
       'PROCEDIMIENTO1', 'PROCEDIMIENTO2', 'IR_29301_COD_GRD', 'IR_29301_PESO',
       'IR_29301_SEVERIDAD', 'IR_29301_MORTALIDAD', 'YEAR', 'EDAD',
       'DIAS_ESTANCIA', 'N_COMORBILIDADES', 'N_PROCEDIMIENTOS',
       'INDICE_CHARLSON', 'DESCRIPCION', 'SECCION', 'COD_REGION', 'REGION',
       'ESTABLECIMIENTO', 'COD_COMUNA', 'COMUNA_ESTAB', 'LATITUD', 'LONGITUD',
       'PRESTADOR', 'COMPLEJIDAD_ESTAB', 'POB_COMUNA', 'POB_REGION',
       'CAMAS_TOTALES', 'CAMAS_CRITICAS', 'POB_MULT_ESTAB',
       'COMUNA_CON_ESTAB_AC', 'FALLECIDO', 'CRITICAS_PROP', 'CAMAS_COMUNA',
       'CRITICAS_COMUNA', 'CAMAS_1000HAB', 'CRITICAS_1000HAB',
       'TASA_MORTALIDAD_COMUNA'],
      dtype='object')

In [23]:
#top 5 diagnosticos más frecuentes en mujeres
top_diagnosticos_femeninos = (
    grd_femenino['DESCRIPCION']
    .value_counts()
    .head(5)
)
top_diagnosticos_femeninos

DESCRIPCION
COVID-19, virus identificado                             12210
Síndrome de dificultad respiratoria del recién nacido     2982
Fractura del cuello de fémur, cerrada                     2834
Leucemia linfoblástica aguda (Todas)                      2232
Enfermedad aterosclerótica del corazón                    1920
Name: count, dtype: Int64

In [27]:
#top 5 diagnosticos mas frecuentes en mujeres por año
top_diagnosticos_femeninos_anio = (
    grd_femenino.groupby('YEAR')['DESCRIPCION'].value_counts().groupby('YEAR').head(5)
)
top_diagnosticos_femeninos_anio

YEAR  DESCRIPCION
2019  Síndrome de dificultad respiratoria del recién nacido     453
      Sepsis no especificada                                    355
      Leucemia linfoblástica aguda (Todas)                      295
      Fractura del cuello de fémur, cerrada                     294
      Enfermedad aterosclerótica del corazón                    272
2020  COVID-19, virus identificado                             3465
      Síndrome de dificultad respiratoria del recién nacido     469
      Fractura del cuello de fémur, cerrada                     341
      Leucemia linfoblástica aguda (Todas)                      335
      Sepsis no especificada                                    291
2021  COVID-19, virus identificado                             7587
      Síndrome de dificultad respiratoria del recién nacido     529
      Fractura del cuello de fémur, cerrada                     423
      Leucemia linfoblástica aguda (Todas)                      353
      Enfermedad aterosclerótica del corazón                    263
2022  COVID-19, virus identificado                              924
      Fractura del cuello de fémur, cerrada                     639
      Síndrome de dificultad respiratoria del recién nacido     586
      Enfermedad aterosclerótica del corazón                    376
      Leucemia linfoblástica aguda (Todas)                      362
2023  Fractura del cuello de fémur, cerrada                     577
      Síndrome de dificultad respiratoria del recién nacido     495
      Enfermedad aterosclerótica del corazón                    442
      Fractura pertrocanteriana, cerrada                        380
      Leucemia linfoblástica aguda (Todas)                      375
2024  Fractura del cuello de fémur, cerrada                     560
      Leucemia linfoblástica aguda (Todas)                      512
      Síndrome de dificultad respiratoria del recién nacido     450
      Fractura pertrocanteriana, cerrada                        402
      Enfermedad aterosclerótica del corazón                    380
Name: count, dtype: int64

In [30]:
#top 5 diagnosticos en mujeres por rango etario
#definir rangos etarios
bins = [0, 18, 30, 45, 60, 75, 90, 120]
labels = ['0-18', '19-30', '31-45', '46-60', '61-75', '76-90', '91-120']
grd_femenino['EDAD'] = pd.cut(grd_femenino['EDAD'], bins=bins, labels=labels, right=False)

top_diagnosticos_femeninos_rango = (
    grd_femenino.groupby('EDAD')['DESCRIPCION'].value_counts().groupby('EDAD').head(5)
)
top_diagnosticos_femeninos_rango

/var/folders/4r/bv24jr955x9g3b9fjjv0bm_c0000gn/T/ipykernel_31005/2589999516.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  grd_femenino['EDAD'] = pd.cut(grd_femenino['EDAD'], bins=bins, labels=labels, right=False)
/var/folders/4r/bv24jr955x9g3b9fjjv0bm_c0000gn/T/ipykernel_31005/2589999516.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grd_femenino.groupby('EDAD')['DESCRIPCION'].value_counts().groupby('EDAD').head(5)
/var/folders/4r/bv24jr955x9g3b9fjjv0bm_c0000gn/T/ipykernel_31005/2589999516.py:8: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  grd_femenino.groupby('EDAD')['DESCRIPCION'].value_counts().groupby('EDAD').head(5)

EDAD    DESCRIPCION
0-18    Síndrome de dificultad respiratoria del recién nacido                     2982
        Leucemia linfoblástica aguda (Todas)                                      1283
        Otros recién nacidos pretérmino                                           1028
        Neumonía debida a virus sincitial respiratorio                             818
        Otro peso bajo al nacer                                                    673
19-30   COVID-19, virus identificado                                               517
        Leucemia linfoblástica aguda (Todas)                                       332
        Leucemia mieloblástica aguda (LMA)                                         159
        Embarazo tubárico                                                          108
        Benzodiazepinas                                                             78
31-45   COVID-19, virus identificado                                              1825
        Leucemia mieloblástica aguda (LMA)                                         207
        Leucemia linfoblástica aguda (Todas)                                       186
        Enfermedad renal crónica, estadio 5                                        176
        Infección consecutiva a procedimiento, no clasificada en otra parte        170
46-60   COVID-19, virus identificado                                              3737
        Enfermedad aterosclerótica del corazón                                     466
        Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas     362
        Infección consecutiva a procedimiento, no clasificada en otra parte        320
        Sepsis no especificada                                                     318
61-75   COVID-19, virus identificado                                              4639
        Enfermedad aterosclerótica del corazón                                    1058
        Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas     564
        Infarto subendocárdico agudo del miocardio                                 546
        Sepsis no especificada                                                     544
76-90   Fractura del cuello de fémur, cerrada                                     1655
        COVID-19, virus identificado                                              1306
        Fractura pertrocanteriana, cerrada                                         925
        Bloqueo auriculoventricular completo                                       648
        Infarto subendocárdico agudo del miocardio                                 382
91-120  Fractura del cuello de fémur, cerrada                                      686
        Fractura pertrocanteriana, cerrada                                         412
        Asistencia y ajuste de marcapaso cardíaco                                  133
        Bloqueo auriculoventricular completo                                       120
        Adherencias [bridas] intestinales con obstrucción                           84
Name: count, dtype: int64

In [31]:

#mujeres vs hombres porcentaje
grd_parquet['SEXO'].value_counts(normalize=True) * 100  # Calcular el porcentaje de mujeres y hombres en el DataFrame parquet

SEXO
HOMBRE         58.011661
MUJER          41.976923
DESCONOCIDO     0.011416
Name: proportion, dtype: float64

In [34]:
grd_masculino = grd_parquet[grd_parquet['SEXO'] == 'HOMBRE']
top_5_diagnosticos_masculinos = (
    grd_masculino['DESCRIPCION']
    .value_counts()
    .head(5)
)
top_5_diagnosticos_masculinos

DESCRIPCION
COVID-19, virus identificado                                              18658
Enfermedad aterosclerótica del corazón                                     6541
Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas     3985
Síndrome de dificultad respiratoria del recién nacido                      3541
Leucemia linfoblástica aguda (Todas)                                       2774
Name: count, dtype: Int64

In [35]:
#top 5 diagnisticos mas frecuentes en hombres por año
top_diagnosticos_masculinos_anio = (
    grd_masculino.groupby('YEAR')['DESCRIPCION'].value_counts().groupby('YEAR').head(5)
)
top_diagnosticos_masculinos_anio

YEAR  DESCRIPCION
2019  Enfermedad aterosclerótica del corazón                                      806
      Síndrome de dificultad respiratoria del recién nacido                       548
      Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas      457
      Sepsis no especificada                                                      426
      Leucemia linfoblástica aguda (Todas)                                        392
2020  COVID-19, virus identificado                                               6099
      Enfermedad aterosclerótica del corazón                                      678
      Síndrome de dificultad respiratoria del recién nacido                       540
      Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas      489
      Leucemia linfoblástica aguda (Todas)                                        426
2021  COVID-19, virus identificado                                              10965
      Enfermedad aterosclerótica del corazón                                      965
      Síndrome de dificultad respiratoria del recién nacido                       633
      Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas      553
      Leucemia linfoblástica aguda (Todas)                                        380
2022  COVID-19, virus identificado                                               1287
      Enfermedad aterosclerótica del corazón                                     1217
      Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas      772
      Síndrome de dificultad respiratoria del recién nacido                       652
      Leucemia linfoblástica aguda (Todas)                                        458
2023  Enfermedad aterosclerótica del corazón                                     1507
      Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas      800
      Síndrome de dificultad respiratoria del recién nacido                       593
      Leucemia linfoblástica aguda (Todas)                                        578
      Infarto subendocárdico agudo del miocardio                                  461
2024  Enfermedad aterosclerótica del corazón                                     1368
      Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas      914
      Infarto subendocárdico agudo del miocardio                                  578
      Síndrome de dificultad respiratoria del recién nacido                       575
      Leucemia linfoblástica aguda (Todas)                                        540
Name: count, dtype: int64

In [38]:
#rangos etarios para hombres
grd_masculino = grd_masculino.copy()

grd_masculino['EDAD'] = pd.cut(
    grd_masculino['EDAD'],
    bins=bins,
    labels=labels,
    right=False
)

top_5_diagnosticos_masculinos_rango = (
    grd_masculino.groupby('EDAD', observed=True)['DESCRIPCION']
    .value_counts()
    .groupby(level='EDAD')
    .head(5)
)
top_5_diagnosticos_masculinos_rango

/var/folders/4r/bv24jr955x9g3b9fjjv0bm_c0000gn/T/ipykernel_31005/1840458123.py:14: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  .groupby(level='EDAD')

EDAD    DESCRIPCION
0-18    Síndrome de dificultad respiratoria del recién nacido                                        3540
        Leucemia linfoblástica aguda (Todas)                                                         1657
        Otros recién nacidos pretérmino                                                              1216
        Neumonía debida a virus sincitial respiratorio                                               1086
        Otro peso bajo al nacer                                                                       703
19-30   COVID-19, virus identificado                                                                  558
        Leucemia linfoblástica aguda (Todas)                                                          459
        Traumatismo del intestino delgado, con herida dentro de la cavidad abdominal                  231
        Traumatismo del hígado y de la vesícula biliar, con herida dentro de la cavidad abdominal     196
        Traumatismo del colon, con herida dentro de la cavidad abdominal                              168
31-45   COVID-19, virus identificado                                                                 2867
        Traumatismo del intestino delgado, con herida dentro de la cavidad abdominal                  323
        Leucemia linfoblástica aguda (Todas)                                                          263
        Infección consecutiva a procedimiento, no clasificada en otra parte                           195
        Hemoneumotórax traumático, con herida dentro de la cavidad torácica                           184
46-60   COVID-19, virus identificado                                                                 6353
        Enfermedad aterosclerótica del corazón                                                       1861
        Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas                       1017
        Infarto transmural agudo del miocardio de la pared anterior                                   681
        Infarto subendocárdico agudo del miocardio                                                    521
61-75   COVID-19, virus identificado                                                                 6827
        Enfermedad aterosclerótica del corazón                                                       3562
        Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas                       1890
        Infarto subendocárdico agudo del miocardio                                                   1213
        Infarto transmural agudo del miocardio de la pared anterior                                  1123
76-90   COVID-19, virus identificado                                                                 1839
        Enfermedad aterosclerótica del corazón                                                        924
        Diabetes mellitus tipo 2 con complicaciones  circulatorias periféricas                        883
        Bloqueo auriculoventricular completo                                                          832
        Infarto subendocárdico agudo del miocardio                                                    555
91-120  Fractura del cuello de fémur, cerrada                                                         173
        Fractura pertrocanteriana, cerrada                                                            117
        Bloqueo auriculoventricular completo                                                          105
        Asistencia y ajuste de marcapaso cardíaco                                                      91
        Síndrome del seno enfermo                                                                      45
Name: count, dtype: int64